name: Deploy to production

on:
  push:
    branches:
      - master

jobs:
  build:
    environment: production
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Create env file
        run: |
          echo "${{ secrets.ENV_VARS }}" > .env
      - name: Build and run the Docker
        run: docker compose up -d --build
